### ISSUE TITLE
Delete the repo?

### ISSUE THREAD

**Issue by limonte** [sweetalert2/swal-not-resolve-in-jest-bug#2]
Many thanks @zenflow for creating this repo!

I guess after https://github.com/sweetalert2/sweetalert2/issues/1426 is resolved and `test.js` file from this repo migrated to https://github.com/sweetalert2/sweetalert2/blob/master/test/jest/jest.test.js we can delete this repo?

**Comment by zenflow** [comment]
@limonte would it be enough to [archive it](https://help.github.com/en/articles/archiving-a-github-repository)? It would appear like [dominictarr/event-stream](https://github.com/dominictarr/event-stream) does. Then the issues (which are now closed) can still be read & understood.

**Comment by limonte** [comment]
Agree9

**Comment by zenflow** [comment]
@limonte doing this now
